Adress a libinjection false positive
DataDog/libddwaf pull request #251
Opened 2024-02-05 10:57 UTC by Taiki-San

2024-02-05 11:13 UTC, Anilm3 requested changes
You'll need to format it using clang-17:

```
cmake .. -DCLANG_FORMAT=/usr/bin/clang-format-17
make format_fix
```

I can do it for you if you need.

2024-02-05 11:13 UTC, Anilm3 commented on tests/matcher/is_sqli_test.cpp
> +        std::cout << match.second << std::endl;
Please remove the print statements.

2024-02-05 12:00 UTC, Taiki-San commented on tests/matcher/is_sqli_test.cpp
> +        std::cout << match.second << std::endl;
Oops, sorry!

2024-02-06 15:21 UTC, Anilm3 commented on src/vendor/libinjection/src/libinjection_sqli.c
> +    sf->hadWordBoundary = stype == TYPE_COMMENT;
`st_assign` uses `memcpy` while `st_assign_char` only had assignments. I think that's why the microbenchmark increased quite a bit:

```
scenario:is_sqli_matcher.random
🟥 execution_time [+477.773µs; +478.102µs] or [+643.703%; +644.145%]
```

2024-02-06 16:47 UTC, Anilm3 approved these changes

2024-02-06 16:53 UTC, merged